#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This module is created just to share global variable among all modules.
"""

gbl_usb_device = ""
gbl_pass = ""
gbl_mbusb_version = ""
gbl_sys_cfg_file = ""
gbl_usb_uuid = ""
usb_mount = ""
password = ""
usb_file_system = ""
zip = ""
iso_file_content = ""
distro = ""
distro_uninstall = ""
cfg_read_err = ""
distro_syslinux_version = ""
syslinux_version = ""
defautl_syslinux_version = ""
distro_syslinux_dir_path = ""
distro_isolinux_bin_path = ""
install_dir = ""
distro_sys_install_bs = ""
mbr_bin = ""
sys_tab = ""
syslinux_options = ""